// Authorization
export const SET_TOKEN = 'SET_TOKEN';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const LOG_OUT = 'LOG_OUT';
export const SET_USER = 'SET_USER';
export const SET_USER_ID = 'SET_USER_ID';
export const FETCH_ACTIVITIES_SUCCESS = 'FETCH_ACTIVITIES_SUCCESS';
export const FETCH_ACTIVITIES_FAIL = 'FETCH_ACTIVITIES_FAIL';
export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS';

// Companies
export const SET__CURRENT_COMPANY_ID = 'SET__CURRENT_COMPANY_ID';
export const ADD_COMPANY_FAIL = 'ADD_COMPANY_FAIL';

// Assets
export const CHANGE_ASSET = 'CHANGE_ASSET';

// Activities
export const ADD_ACTIVITY_FAIL = 'ADD_ACTIVITY_FAIL';
export const SET_CURRENT_ACTIVITY_ID = 'SET_CURRENT_ACTIVITY_ID';

//Type
export const GET_TYPES_SUCCESS = 'GET_TYPES_SUCCESS';
export const GET_TYPES_FAIL = 'GET_TYPES_FAIL';

//Stage
export const ADD_STAGE = 'ADD_STAGE';
export const ADD_STAGE_FAIL = 'ADD_STAGE_FAIL';
export const UPDATE_STAGE_FAIL = 'UPDATE_STAGE_FAIL';
